### ISSUE TITLE
Retries on GRPC errors?

### ISSUE THREAD

**Issue by pselden** [google/ml-metadata#50] opened 2020-07-31 15:06 UTC
I have a TFX pipeline on Kubeflow using BigQueryExampleGen that is frequently failing because of a GRPC error:

```
	details = "mysql_query failed: errno: 2013, error: Lost connection to MySQL server during query"
	debug_error_string = "{"created":"@1596203848.918267726","description":"Error received from peer ipv4:172.28.140.89:8080","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"mysql_query failed: errno: 2013, error: Lost connection to MySQL server during query","grpc_status":13}"
>
```

Unfortunately it looks like retry logic only checks for a specific type of AbortError when deciding or not to retry. Is it possible to get it extended to other error types to handle possible transient errors like this?

Below is the full stack trace:

```
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 378, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 371, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 197, in launch
    self._exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 166, in _run_driver
    component_info=self._component_info)
  File "/tfx-src/tfx/components/base/base_driver.py", line 239, in pre_execution
    pipeline_info)
  File "/tfx-src/tfx/orchestration/metadata.py", line 1062, in register_pipeline_contexts_if_not_exists
    _CONTEXT_TYPE_KEY_PIPELINE_NAME: pipeline_info.pipeline_name
  File "/tfx-src/tfx/orchestration/metadata.py", line 980, in _register_context_if_not_exist
    properties=properties)
  File "/tfx-src/tfx/orchestration/metadata.py", line 945, in _prepare_context
    (k, property_type_mapping[type(k)]) for k, v in properties.items()))
  File "/tfx-src/tfx/orchestration/metadata.py", line 922, in _register_context_type_if_not_exist
    context_type, can_add_fields=True)
  File "/opt/venv/lib/python3.6/site-packages/ml_metadata/metadata_store/metadata_store.py", line 463, in put_context_type
    self._call('PutContextType', request, response)
  File "/opt/venv/lib/python3.6/site-packages/ml_metadata/metadata_store/metadata_store.py", line 131, in _call
    return self._call_method(method_name, request, response)
  File "/opt/venv/lib/python3.6/site-packages/ml_metadata/metadata_store/metadata_store.py", line 162, in _call_method
    raise _make_exception(e.details(), e.code().value[0])
tensorflow.python.framework.errors_impl.InternalError: mysql_query failed: errno: 2013, error: Lost connection to MySQL server during query
```

**Comment by hughmiao** [comment] 2020-07-31 21:27
We treat special error code as aborted, e.g., 1213, 1205; 
For 2013, it means connection/query timeout. Retry probably won't help much. The failed query in the log simply insert one row.  Consider to adjust mysql settings in the deployment? [1]. cc some tfx folks @ruoyu90, @1025KB

[1] https://dev.mysql.com/doc/refman/5.7/en/error-lost-connection.html

**Comment by calvinleungyk** [comment] 2020-08-14 21:56
I'm having a similar issue with Beam executing on dataflow workers. @pselden were you able to resolve the issue with adjusting mysql settings?

**Comment by pselden** [comment] 2020-08-17 17:49
Fortunately (or unfortunately) the issue just suddenly stopped happening, and I didn't have to adjust anything else.

**Comment by casassg** [comment] 2020-08-18 18:21
What version of MLMD/TFX are you on @pselden ? Did you do any upgrade change in your MySQL instance?

Wondering if this may be caused by gRPC server holding the connection for too long?

**Comment by hughmiao** [comment] 2020-08-19 01:19
thanks, @pselden and @casassg . @casassg, on the server changes, the current behavior of gRPC server after 0.22.1+ is a short held connection per transaction after commit https://github.com/google/ml-metadata/commit/5093603a6c133f79245426837090dd0130004825 .
For the previous releases, the connection was long lived, and we saw the stale connection from long lived UI servers returning 2006 error code. In 0.22.0, the long holding connection was supported via reconnection after commit https://github.com/google/ml-metadata/commit/85ad360bc6ba876425b1220b8228b456362b916c . Probably it is helpful to diagnosis your case.

**Comment by pselden** [comment] 2020-08-19 16:15
We were on tfx:0.21.2. I will try this later version. Thanks!

**Comment by hughmiao** [comment] 2020-08-24 16:17
sg. good to know. close it now. Please feel free to reopen.

**Closed by hughmiao** 2020-08-24 16:17 UTC
