### ISSUE TITLE
Issues building locally on a Mac 

### ISSUE THREAD

**Issue by ddutta** [google/ml-metadata#2] opened 2019-01-24 02:42 UTC
Followed the guide, installed bazel etc and tried .... 

$ bazel run -c opt --define grpc_no_ares=true ml_metadata:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 86e0a52a-beab-4a71-869b-f28cae05bd0c
ERROR: /private/var/tmp/_bazel_dedutta/20c43d1af01a72b975f0b1d572e55dd8/external/protobuf_archive/BUILD:591:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dedutta/20c43d1af01a72b975f0b1d572e55dd8/external/protobuf_archive/BUILD", line 591
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/private/var/tmp/_bazel_dedutta/20c43d1af01a72b975f0b1d572e55dd8/external/protobuf_archive/protobuf.bzl", line 269, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/private/var/tmp/_bazel_dedutta/20c43d1af01a72b975f0b1d572e55dd8/external/protobuf_archive/protobuf.bzl", line 269, in Label
		REPOSITORY_NAME
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
ERROR: /private/var/tmp/_bazel_dedutta/20c43d1af01a72b975f0b1d572e55dd8/external/protobuf_archive/BUILD:373:1: Target '@protobuf_archive//:android' contains an error and its package is in error and referenced by '@protobuf_archive//:protoc'
ERROR: /private/var/tmp/_bazel_dedutta/20c43d1af01a72b975f0b1d572e55dd8/external/protobuf_archive/BUILD:373:1: Target '@protobuf_archive//:msvc' contains an error and its package is in error and referenced by '@protobuf_archive//:protoc'
ERROR: /Users/dedutta/work/ml-metadata/ml_metadata/proto/BUILD:42:1: Target '@protobuf_archive//:protobuf_python_genproto' contains an error and its package is in error and referenced by '//ml_metadata/proto:metadata_store_py_pb2_genproto'
ERROR: /Users/dedutta/work/ml-metadata/ml_metadata/proto/BUILD:42:1: Target '@protobuf_archive//:protoc' contains an error and its package is in error and referenced by '//ml_metadata/proto:metadata_store_py_pb2_genproto'
ERROR: Analysis of target '//ml_metadata:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 14.508s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (14 packages loaded, 40 targets co\
FAILED: Build did NOT complete successfully (14 packages loaded, 40 targets co\
nfigured)
    currently loading: @org_tensorflow//tensorflow/core
    Fetching @swig; fetching
    Fetching @local_config_python; fetching
    Fetching @local_config_cc; Restarting.

**Comment by hughmiao** [comment] 2019-05-30 21:53
The issue is resolved in last release. Close this for now. Please feel free to reopen.

**Closed by hughmiao** 2019-05-30 21:53 UTC
