### ISSUE TITLE
Find Execution w/ where clause (how to load state)

### ISSUE THREAD

**Issue by eggie5** [google/ml-metadata#100] opened 2021-01-25 02:15 UTC
Let's say I have this simple flow: `Trainer` -> `Evaluator` in a DAG pipeline.

The `Trainer` Execution logs a `Model` Artifact and ends. Then, next for the `Evaluator` Execution to run, it's going to need some state about what happened in the previous `Trainer` Execution step, ie where is the saved model on disk.

Now the only way, w/ the MLMD ORM, to pull an arbitrary Execution is to query it by primary key, eg `get_executions_by_id`. 

Now, how is the `Evaluator` supposed to know the `Trainer` Execution primary key? There's no state.

I could log a global state variable like `flow_exec_id` that my pipeline system generates and add it as property of the Trainer Execution. Then I could do a lookup w/ a where clause on `flow_exec_id=1` property of the Execution. However, the MLMD ORM doesn't expose a where clause. 

How should I do this? 

The workaround I can think of, is to do `get_executions()` and filter `flow_exec_id` in python (instead of the backend DB). 

Very curious how TFX makes this work w/ Airflow. I'm using Azkaban where you can't pass variables between stages. Maybe you can in Airflow??

**Comment by hughmiao** [comment] 2021-01-25 21:06
Alex, this is a duplicate of https://github.com/google/ml-metadata/issues/68. We will oss declarative apis to filter executions. Please stay tuned. 

> Then, next for the Evaluator Execution to run, it's going to need some state about what happened in the previous Trainer Execution step, ie where is the saved model on disk.

If you are not using tfx for orchestration instead using mlmd directly, one good practice is to describe a pipeline run with mlmd context, i.e., the trainer, and evaluator are belong to a pipeline run mlmd.context, which can latter be used to list all relevant executions, e.g., using mlmd traversal apis, `get_executions_by_context`. The (context.type, context.name) is unique. Only the pipeline context's id or name need to be passed through.  This also helps with mixing pipelines runs on a single db.

**Comment by eggie5** [comment] 2021-01-26 21:59
@hughmiao thanks for answering my questions. It does indeed seem like #68 generalizes my use-case. Also using a context as a proxy for my pipeline/flow would work.

I'm using Azkaban. I'm curious how TFX passes state between stages w/ Aireflow for example. Does it do this context trick you described?

**Comment by hughmiao** [comment] 2021-01-27 18:27
>  thanks for answering my questions. It does indeed seem like #68 generalizes my use-case. Also using a context as a proxy for my pipeline/flow would work.

sg. let's close this and follow up in #68. 

> I'm using Azkaban. I'm curious how TFX passes state between stages w/ Aireflow for example. Does it do this context trick you described?

yes, the tfx component has pipeline info (e.g., mlmd context names, file path directories, etc), at run time, all executions/artifacts of related contexts can be queried. The component can choose to skip or abort depending on the lineage history. You may find the [implementation details](https://github.com/tensorflow/tfx/blob/5adc9b7434ace62e98df621e35216d70216f68e0/tfx/orchestration/airflow/airflow_dag_runner.py) useful too.

**Closed by hughmiao** 2021-01-27 18:27 UTC
